version: "2.4"

services:
  server:
    build:
      context: ./server
    ports:
      - 3000:3000
  proxy:
    build:
      context: ./proxy
    ports:
      - 3001:3001
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=3000

    
